steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "src/apis/backend.$_BRANCH.js", "src/apis/backend.js"]
  - name: gcr.io/cloud-builders/gsutil
    args:
      [
        "cp",
        "src/components/form/Recaptcha.$_BRANCH.js",
        "src/components/form/Recaptcha.js",
      ]
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "npm"
    args: ["run", "build"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "deployment/app.$_BRANCH.yaml", "app.yaml"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
