# GCloud build must define $_ENVIRONMENT to either "staging" or "prod"

steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "src/apis/backend.$_ENVIRONMENT.js", "src/apis/backend.js"]
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "npm"
    args: ["run", "build"]
  - name: gcr.io/cloud-builders/gsutil
    # $BRANCH_NAME is automatically defined by GCloud Build.
    # https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values
    # We use $BRANCH_NAME instead of $_ENVIRONMENT because the app.yaml for staging and map-staging is different.
    args: ["cp", "deployment/app.$BRANCH_NAME.yaml", "app.yaml"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
