steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "src/apis/backend.$_ENVIRONMENT.js", "src/apis/backend.js"]
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "npm"
    args: ["run", "build"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["cp", "deployment/app.$BRANCH_NAME.yaml", "app.yaml"] # Branch name to use map-staging app config
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
